conversione_mi_km: conversione_mi_km.c Makefile
	gcc -ansi -Wall -O conversione_mi_km.c -o conversione_mi_km

pulisci:
	rm -f conversione_mi_km.o
	
pulisci_tutto:
	rm -f conversione_mi_km conversione_mi_km.o
