livello_radiazioni: livello_radiazioni.c Makefile
	gcc -ansi -Wall -O livello_radiazioni.c -o livello_radiazioni
pulisci:
	rm -f livello_radiazioni.o
	
pulisci_tutto:
	rm -f livello_radiazioni livello_radiazioni.o
