generatore_listato: generatore_listato.c Makefile
	gcc -ansi -Wall -O generatore_listato.c -o generatore_listato

pulisci:
	rm -f generatore_listato.o
	
pulisci_tutto:
	rm -f generatore_listato generatore_listato.o
